# From https://github.com/mikechernev/dockerised-php
version: '2'

services:
    web:
        image: nginx:alpine
        restart: always
        ports:
            - "8020:80"
        volumes:
            - ../:/code
            # This overrides the dir with empty temp volumes
            - /code/configs
            - /code/reports
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm-alpine
        restart: always
        volumes:
            - ../:/code
