# From https://github.com/mikechernev/dockerised-php
version: '2'

services:
    web:
        image: nginx:alpine
        ports:
            - "8020:80"
        volumes:
            - ../:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm-alpine
        volumes:
            - ../:/code
